[package]
name = "pve-xtermjs"
version = "4.7.0"
authors = [
    "Dominik Csapak <d.csapak@proxmox.com>",
    "for xterm.js parts: The xterm.js authors <https://github.com/xtermjs/xterm.js>",
]
edition = "2018"
license = "AGPL-3"

exclude = [ "build", "debian" ]

[dependencies]
mio = { version = "0.7", features = [ "net", "os-ext" ] }
curl = "0.4"
clap = "2.33"
#proxmox = { version = "0.10.0", default-features = false }
proxmox = { path = "../proxmox/proxmox", default-features = false }
